# https://appengine.google.com/dashboard/nonedeployed?app_id=s~provapaccap
# locally: dev~provapaccap
# remote: http://provapaccap.appspot.com/
#application: provapaccap
#version: 104
runtime: php55
api_version: 1

# Tips(y): http://gaeforphp-blog.appspot.com/
default_expiration: "1d"

handlers:
- url: /(.*\.(ico$|jpg$|png$|gif$|css$))
  static_files: static/\1
  upload: static/(.*\.(ico$|jpg$|png$|gif$|css$))
  application_readable: true
- url: /
  script: app/index.php
- url: /index
  script: app/index.php
- url: /home
  script: app/index.php
- url: /redirec.*
  script: app/redirect.php
- url: /hello
  script: app/hello.php
- url: /cloud_storage
  script: app/cloud_storage.php
- url: /cloud_sql
  script: app/cloud_sql.php
- url: /posts
  script: app/posts.php
- url: /posts/.*
  script: app/posts-view.php
- url: /phpinfo
  script: app/phpinfo.php
- url: /static/stylesheets
  static_dir: stylesheets
#- url: /favicon.ico
#  script: favicon.ico
