# https://appengine.google.com/dashboard/nonedeployed?app_id=s~provapaccap
# locally: dev~provapaccap
# remote: http://provapaccap.appspot.com/
application: provapaccap
version: 5
runtime: php
api_version: 1

# Tips(y): http://gaeforphp-blog.appspot.com/
default_expiration: "1d"

handlers:
- url: /(.*\.(ico$|jpg$|png$|gif$))
  static_files: static/\1
  upload: static/(.*\.(ico$|jpg$|png$|gif$))
  application_readable: true
- url: /
  script: index.php
- url: /hello
  script: hello.php
- url: /phpinfo
  script: phpinfo.php
- url: /static/stylesheets
  static_dir: stylesheets
#- url: /favicon.ico
#  script: favicon.ico
