# https://appengine.google.com/dashboard/nonedeployed?app_id=s~provapaccap
application: provapaccap
version: 3
runtime: php
api_version: 1

handlers:
- url: /
  script: index.php
- url: /hello
  script: hello.php
- url: /phpinfo
  script: phpinfo.php
- url: /favicon.ico
  script: favicon.ico
